import { parseJsonBody, withApiHandler } from "@/lib/api";
import { requireUser } from "@/lib/auth";
import { updateTaskSchema } from "@/lib/schemas";
import { deleteTask, getTask, updateTask } from "@/services/server";

export const dynamic = "force-dynamic";

/**
 * `params` is a Promise in Next.js 16 — synchronous access was removed.
 * `RouteContext<'…'>` is generated by `next typegen`; it needs no import.
 */
type Context = RouteContext<"/api/v1/tasks/[id]">;

export const GET = withApiHandler<Context>(async (request, context) => {
  const { uid } = await requireUser(request);
  const { id } = await context.params;

  return getTask(uid, id);
});

/** Covers status change, priority change, project assignment and tag edits. */
export const PATCH = withApiHandler<Context>(async (request, context) => {
  const { uid } = await requireUser(request);
  const { id } = await context.params;
  const input = await parseJsonBody(request, updateTaskSchema);

  return updateTask(uid, id, input);
});

export const DELETE = withApiHandler<Context>(async (request, context) => {
  const { uid } = await requireUser(request);
  const { id } = await context.params;

  return deleteTask(uid, id);
});
