import type { Metadata } from "next";

import { TaskDetail } from "@/components/tasks/task-detail";

export const metadata: Metadata = {
  title: "פרטי משימה",
};

/**
 * `params` is a Promise in Next.js 16 — synchronous access was removed.
 * `PageProps<'…'>` is generated by `next typegen` and needs no import.
 */
export default async function TaskPage(props: PageProps<"/tasks/[id]">) {
  const { id } = await props.params;

  return <TaskDetail taskId={id} />;
}
