import type { Metadata } from "next";
import { Fredoka, Rubik } from "next/font/google";

import { AppProviders } from "@/components/providers/app-providers";

import "./globals.css";

/**
 * Brand typefaces. Both ship a genuine Hebrew subset, so the Hebrew UI renders
 * in the brand faces rather than falling back to a system font.
 *
 * Rubik handles body copy and dense UI; Fredoka carries headings and buttons.
 */
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["hebrew", "latin"],
  display: "swap",
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["hebrew", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="he"
      dir="rtl"
      className={`${rubik.variable} ${fredoka.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
